version: '3'
services: 
  nodejs-server:
    build:
      context: ./api
    ports:
      - "3080:3080"
    container_name: node-api
    volumes:
      - ./api:/usr/src/app/api
      - /usr/src/app/node_modules
  next-ui:
    build:
      context: ./my-app
    ports: 
      - "8080:8080"
    container_name: next-ui
    stdin_open: true
    volumes:
      - ./my-app:/usr/src/app/my-app
      - /usr/src/app/my-app/node_modules